before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./main.go
    ldflags:
      - -s -w
      - -X github.com/kobtea/sample-github-actions/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - docker.pkg.github.com/kobtea/sample-github-actions/main:latest
      - docker.pkg.github.com/kobtea/sample-github-actions/main:v{{ .Major }}
      - docker.pkg.github.com/kobtea/sample-github-actions/main:{{ .Tag }}
      - ghcr.io/kobtea/sample-github-actions:latest
      - ghcr.io/kobtea/sample-github-actions:v{{ .Major }}
      - ghcr.io/kobtea/sample-github-actions:{{ .Tag }}
    dockerfile: Dockerfile.goreleaser
nfpms:
  - homepage: https://github.com/kobtea/sample-github-actions
    maintainer: Hiroaki Kobayashi <kobtea9696@gmail.com>
    description: sample github actions
    license: MIT
    formats:
      - deb
      - rpm
