before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./main.go
    ldflags:
      - -s -w
      - -X github.com/kobtea/sample-github-actions/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      # - docker.pkg.github.com/kobtea/sample-github-actions/main:latest-amd64
      # - docker.pkg.github.com/kobtea/sample-github-actions/main:v{{ .Major }}-amd64
      # - docker.pkg.github.com/kobtea/sample-github-actions/main:{{ .Tag }}-amd64
      - ghcr.io/kobtea/sample-github-actions:latest-amd64
      - ghcr.io/kobtea/sample-github-actions:v{{ .Major }}-amd64
      - ghcr.io/kobtea/sample-github-actions:{{ .Tag }}-amd64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Tag}}
      - --platform=linux/amd64
  - goos: linux
    goarch: arm64
    image_templates:
      # - docker.pkg.github.com/kobtea/sample-github-actions/main:latest-arm64
      # - docker.pkg.github.com/kobtea/sample-github-actions/main:v{{ .Major }}-arm64
      # - docker.pkg.github.com/kobtea/sample-github-actions/main:{{ .Tag }}-arm64
      - ghcr.io/kobtea/sample-github-actions:latest-arm64
      - ghcr.io/kobtea/sample-github-actions:v{{ .Major }}-arm64
      - ghcr.io/kobtea/sample-github-actions:{{ .Tag }}-arm64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Tag}}
      - --platform=linux/arm64
docker_manifests:
  # - name_template: docker.pkg.github.com/kobtea/sample-github-actions/main:latest
  #   image_templates:
  #     - docker.pkg.github.com/kobtea/sample-github-actions/main:latest-amd64
  #     - docker.pkg.github.com/kobtea/sample-github-actions/main:latest-arm64
  # - name_template: docker.pkg.github.com/kobtea/sample-github-actions/main:v{{ .Major }}
  #   image_templates:
  #     - docker.pkg.github.com/kobtea/sample-github-actions/main:v{{ .Major }}-amd64
  #     - docker.pkg.github.com/kobtea/sample-github-actions/main:v{{ .Major }}-arm64
  # - name_template: docker.pkg.github.com/kobtea/sample-github-actions/main:{{ .Tag }}
  #   image_templates:
  #     - docker.pkg.github.com/kobtea/sample-github-actions/main:{{ .Tag }}-amd64
  #     - docker.pkg.github.com/kobtea/sample-github-actions/main:{{ .Tag }}-arm64
  - name_template: ghcr.io/kobtea/sample-github-actions:latest
    image_templates:
      - ghcr.io/kobtea/sample-github-actions:latest-amd64
      - ghcr.io/kobtea/sample-github-actions:latest-arm64
  - name_template: ghcr.io/kobtea/sample-github-actions:v{{ .Major }}
    image_templates:
      - ghcr.io/kobtea/sample-github-actions:v{{ .Major }}-amd64
      - ghcr.io/kobtea/sample-github-actions:v{{ .Major }}-arm64
  - name_template: ghcr.io/kobtea/sample-github-actions:{{ .Tag }}
    image_templates:
      - ghcr.io/kobtea/sample-github-actions:{{ .Tag }}-amd64
      - ghcr.io/kobtea/sample-github-actions:{{ .Tag }}-arm64
nfpms:
  - homepage: https://github.com/kobtea/sample-github-actions
    maintainer: Hiroaki Kobayashi <kobtea9696@gmail.com>
    description: sample github actions
    license: MIT
    formats:
      - deb
      - rpm
