name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CGO_ENABLED: 0

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - run: go get -v -t -d ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          args: -E gofmt,goimports

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - run: go get -v -t -d ./...

      - name: Build
        run: make build

      - name: Test
        run: make test
  #  tag-major:
  #    name: tag major
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: kobtea/release-tag-action@master
  #        with:
  #          force: true
  #          only_major_version: true
  tag-full:
    name: tag full
    needs:
      - lint
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - uses: kobtea/release-tag-action@master
        with:
          message: gogo __VERSION__
